# ===========================
# Core: languages, sitemap, outputs, permalinks, markdown, privacy, performance
# ===========================
title = "Hackitect7 — The Music of Systems"
languageCode = "en-us"
defaultContentLanguage = "us"
defaultContentLanguageInSubdir = true
enableGitInfo = true

# Важно: абсолютные канонические URL (улучшает каноникал/дубликаты)
relativeURLs = false
canonifyURLs = true

# Точка данных для твоего t.html (кастомная i18n-логика)
dataDir = "locales"

# Пагинация
[pagination]
  pagerSize = 10

# Таксономии
[taxonomies]
  tag = "tags"
  category = "categories"

# Карта сайта
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Выходные форматы
[outputs]
  home = ["HTML", "RSS", "JSON"]   # JSON пригодится для виджетов/индексов
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]
  page = ["HTML"]

# ЧПУ-ссылки
# БЛОГ без дат — лучше для evergreen/маркетинга и сниппетов; ссылки стабильнее
[permalinks]
  blog = "/blog/:slug/"
  projects = "/projects/:slug/"
  services = "/services/:slug/"

# Markdown / TOC
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

# Privacy
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

# Производительность (Hugo Pipes / изображения)
[minify]
  minifyOutput = true

[imaging]
  quality = 82
  resampleFilter = "Lanczos"
