baseURL = "https://hackitect7.github.io/"
title = "Hackitect7 — The Music of Systems"
languageCode = "en-us"
defaultContentLanguage = "us"
defaultContentLanguageInSubdir = true
enableGitInfo = true
relativeURLs = false
canonifyURLs = false
dataDir = "locales"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  projects = "/projects/:slug/"
  services = "/services/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true
