name: Deploy Hugo site to Pages (prod)

on:
  push:
    branches: ["main"] # деплой только с main
  pull_request:
    branches: ["main"] # сборка-проверка на PR
  workflow_dispatch: # ручной запуск

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Setup Hugo (match local)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.149.1"
          extended: true

      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: |
            resources/_gen
            .hugo_cache
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/*.html','**/*.md','**/*.toml','**/*.yaml','**/*.yml','static/assets/**/*') }}

      # Вычисляем корректный baseURL для GitHub Pages (user/org vs project)
      - name: Compute baseURL for GitHub Pages
        id: pages
        shell: bash
        run: |
          OWNER_LC="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          REPO="${GITHUB_REPOSITORY#*/}"
          if [ "$REPO" = "${OWNER_LC}.github.io" ]; then
            BASE="https://${OWNER_LC}.github.io/"
          else
            BASE="https://${OWNER_LC}.github.io/${REPO}/"
          fi
          echo "baseurl=${BASE}" >> "$GITHUB_OUTPUT"
          echo "Resolved baseURL: ${BASE}"

      # Прод-сборка: берём твой production-конфиг и подставляем корректный baseURL
      - name: Build (production)
        run: >
          hugo --minify --gc
          --environment production
          --config config/production/config.toml
          --baseURL "${{ steps.pages.outputs.baseurl }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
